// AUTO-GENERATED by `loom gen` from app/flows/**/flow.ts — the folder convention,
// resolved at BUILD time (static imports), so the flow set is identical on every
// resume / remote worker. Run `pnpm gen` after adding a flow.
import * as _f0 from "./flows/migration-guard/flow";

export const flowModules = [_f0];
