// AUTO-GENERATED by `loom gen`. Do not edit by hand.
// Static modules for defineConfig — flows/agents/tools/skills/schedules/memories/projections.
import * as _f0 from "./flows/migration-guard/flow";

export const flowModules = [_f0];


export const agentModules = [];


export const toolModules = [];


export const skillModules = [];


export const scheduleModules = [];


export const memoryModules = [];


export const projectionModules = [];
