import { type StorageConfig, defineConfig } from "@loom/app";
import { retryMiddleware } from "@loom/middleware";
// AUTO-GENERATED by `loom gen` from app/flows/**/flow.ts — static imports, so the
// flow set is identical on every resume / remote worker. Run `pnpm gen` to refresh.
import { flowModules } from "../app/loom.gen";

export type LoomApp = ReturnType<typeof defineConfig>;

// `ctx.ui.*` in a flow targets the default agent surface, "ui" — loom's own patch protocol,
// not the Google A2UI wire protocol (`@loom/plugin-a2ui` is the adapter for that).
export const SURFACES = ["ui"];

// The caller supplies a storage descriptor. `@loom/app` names no vendor (ADR 0043): a backend
// is a PRESET returning `{ kind: "custom", … }` — `sqliteStorage({ dir })` from
// `@loom/plugin-sqlite`, `postgresStorage({ url })` from `@loom/plugin-postgres`, or your own.
// Keeping the choice at the call site is also what keeps better-sqlite3/node:fs out of the
// browser bundle, since this module is shared with the React surface.
export type StorageOpt = StorageConfig;

/**
 * The composition root. `defineConfig` assembles the durable runtime, stores,
 * effect middleware, projection runtime, and A2A bus from this static config and
 * returns a `LoomApp` — the same assembly the headless driver (src/main.ts) and
 * the React UI (src/browser) both consume. One brain, two surfaces.
 */
export function buildApp(opts?: { storage?: StorageOpt }): LoomApp {
  return defineConfig({
    storage: opts?.storage ?? { kind: "memory" },
    surfaces: SURFACES,
    flowModules,
    // Every effect (each step handler) gets exponential backoff + deterministic jitter.
    execution: {
      effectMiddleware: [
        retryMiddleware({ maxRetries: 3, baseDelayMs: 50, factor: 2, jitter: true }),
      ],
    },
    // Static flow-graph checks at boot (missing effects, dangling capabilities).
    checks: { validate: "warn" },
  });
}
