import { defineConfig } from "@loom/app";
import { retryMiddleware } from "@loom/middleware";
// AUTO-GENERATED by `loom gen` from app/flows/**/flow.ts — static imports, so the
// flow set is identical on every resume / remote worker. Run `pnpm gen` to refresh.
import { flowModules } from "../app/loom.gen";

export type LoomApp = ReturnType<typeof defineConfig>;

// `ctx.ui.*` in a flow targets the default A2UI surface, "ui".
export const SURFACES = ["ui"];

export type StorageOpt = { kind: "memory" } | { kind: "sqlite"; dir: string; branching?: boolean };

/**
 * The composition root. `defineConfig` assembles the durable runtime, stores,
 * effect middleware, projection runtime, and A2A bus from this static config and
 * returns a `LoomApp` — the same assembly the headless driver (src/main.ts) and
 * the React UI (src/browser) both consume. One brain, two surfaces.
 */
export function buildApp(opts?: { storage?: StorageOpt }): LoomApp {
  return defineConfig({
    storage: opts?.storage ?? { kind: "memory" },
    surfaces: SURFACES,
    flowModules,
    // Every effect (each step handler) gets exponential backoff + deterministic jitter.
    effectMiddleware: [
      retryMiddleware({ maxRetries: 3, baseDelayMs: 50, factor: 2, jitter: true }),
    ],
    // Static flow-graph checks at boot (missing effects, dangling capabilities).
    validate: "warn",
  });
}
